### ISSUE TITLE
Images from gzipped files cannot be copied if data have been read

### ISSUE THREAD

**Issue by tsalo** [nipy/nibabel#969] opened 2020-11-17 20:36 UTC
I am trying to deep-copy an object with a `nilearn` `NiftiMasker` as an attribute, and I'm coming up against an issue only when the `NiftiMasker` is derived from a `nii.gz` file (see https://github.com/neurostuff/NiMARE/issues/399 for more info). After doing some digging, I think that the problem arises on `nibabel`'s end, where an img from a gzipped file cannot be deep-copied when the data has been accessed.

I am using `nibabel` version 3.2.0 and `indexed_gzip` version 1.3.3.

To reproduce:

```python
from copy import deepcopy
 
import nibabel as nib
import numpy as np

# Create nii and nii.gz files with the same contents
generated_img = nib.Nifti1Image(np.random.random((10, 10, 10)), affine=np.eye(4))
generated_img.to_filename('test.nii')
generated_img.to_filename('test.nii.gz')

# Test the unzipped file
img = nib.load('test.nii')
img_copy = deepcopy(img)  # no error
data = img.get_fdata()  # load the data, *without touching it*
deepcopy(img_copy)  # no error
deepcopy(img)  # no error

# Test the nii.gz file
gz_img = nib.load('test.nii.gz')
gz_img_copy = deepcopy(gz_img)  # no error
data = gz_img.get_fdata()  # load the data, *without touching it*
deepcopy(gz_img_copy)  # no error
deepcopy(gz_img)  # error
```

**Comment by effigies** [comment] 2020-11-17 20:46
Does this reproduce when `indexed_gzip` is not installed?

**Comment by tsalo** [comment] 2020-11-17 20:51
No it does not. I can also avoid it with a workaround provided by @rmarkello:

```python

import gzip
import nibabel as nib

nib.openers.HAVE_INDEXED_GZIP = False
nib.openers.IndexedGzipFile = gzip.GzipFile

...  # everything else
```

**Comment by effigies** [comment] 2020-11-17 21:10
Okay, I'm going to cc @pauldmccarthy then. This looks like an unsafe deepcopy of `IndexedGzipFile`.

**Comment by pauldmccarthy** [comment] 2020-12-18 16:55
@effigies @tsalo apologies for missing the ping on Nov 17 - I must have had a blind spot when it hit my email inbox! Will resolve this over at pauldmccarthy/indexed_gzip#50 ..

**Comment by effigies** [comment] 2020-12-18 18:12
I think I'll close this here, since it's being tracked in NiMARE and fixed in indexed_gzip.

**Closed by effigies** 2020-12-18 18:12 UTC
