### ISSUE TITLE
More options for the mmap keyword to load

### ISSUE THREAD

**Issue by matthew-brett** [nipy/nibabel#330] opened 2015-07-20 17:32 UTC
This is from the discussion at the developer hangout.

Yarik was wondering whether it was possible to have `mmap='enforce'` mode for `load`.

This would try and mmap the image data, and raise an error if that was not possible.

Another option Yarik wondered about was read / write memory mapping, where writing to the array changes the file on disk.

**Comment by matthew-brett** [comment] 2015-07-20 20:49
Investigating, it is possible to use 'r+' mode to `np.memmap`, and this does seem to work in changing the underlying file.

**Comment by matthew-brett** [comment] 2015-07-21 00:00
mmap PR is https://github.com/nipy/nibabel/pull/268

Discussion starting from http://mail.scipy.org/pipermail/nipy-devel/2014-October/010377.html and http://mail.scipy.org/pipermail/nipy-devel/2014-November/010381.html

I see from the current code and my edits that I allow 'r+' mode in the `array_from_file` low-level function, but disallow it from the image class load and array proxy creation.  I remember doing this explicitly, for some reason to do with the potential API problems that could result, but I don't remember what they were, and I don't seem to have recorded them anywhere.

**Comment by effigies** [comment] 2015-07-21 15:23
It seems to me that an 'r+' option should error out when `mmap`ing fails, rather than default to an in-memory array, since the expected behavior is that a change to the array results in a change on disk. This applies to the existing `array_from_file` as well as the possible change to `load`.

**Comment by effigies** [comment] 2017-10-14 02:37
I think this should have been closed by #268.

**Closed by effigies** 2017-10-14 02:37 UTC
