### ISSUE TITLE
Pre-release job is failing against master

### ISSUE THREAD

**Issue by jacobdr** [nipy/nibabel#1108] opened 2022-05-08 05:12 UTC
[most recent failing job as of this writing May 7](https://github.com/nipy/nibabel/actions/runs/2288182520)

Trying to narrow differences... since `mmap` is coming from the standard lib I suspected a change in Python versions and how `repr(mmap_obj)` or `str(mmap_obj)` is displayed... Its possible, though still smells to me so needs a sanity check. 

As evidence, though, comparing against a prior (chose #1096 as the most recent unmerged green build I saw....)

**Python version comparison**

  * [3.10.4 this MR](https://github.com/nipy/nibabel/runs/6336648709?check_suite_focus=true#step:3:12) vs [3.10.2 prior success](https://github.com/nipy/nibabel/runs/5739141260?check_suite_focus=true#step:3:12)
  * [3.9.12 this MR](https://github.com/nipy/nibabel/runs/6336648414?check_suite_focus=true#step:3:12) vs [3.9.10 prior success](https://github.com/nipy/nibabel/runs/5739141130?check_suite_focus=true#step:3:12)
  * the [scheduled pre-release cron job against master](https://github.com/nipy/nibabel/actions/runs/2288182520) is failing for the same reason.

Final note: the only pre-release job that passes is the one that does not have the PRE_PIP_FLAGS environment variable set....

_Originally posted by @jacobdr in https://github.com/nipy/nibabel/pull/1105#issuecomment-1120350450_

**Comment by effigies** [comment] 2022-05-09 13:02
Manually bisecting the pre-release wheels of numpy (https://pypi.anaconda.org/scipy-wheels-nightly/simple/numpy/) I can say that this arose between numpy-1.23.0.dev0+1065.gf996a2b62 and numpy-1.23.0.dev0+1087.g0eaa40db3.

Looking at https://github.com/numpy/numpy/compare/f996a2b62...0eaa40db3, I see they merged https://github.com/numpy/numpy/pull/21324 in that interval, which seems likely to be the cause. It does not look like it actually performs a copy, so that's probably okay. It looks like the reason the test was written this way:

    NetCDF files, when opened read-only, return arrays that refer
    directly to memory-mapped data on disk:

        >>> data = time[:]
        >>> data.base.base  # doctest: +ELLIPSIS
        <mmap.mmap ...>

is because the object is not actually a `numpy.memmap` but a custom `mmap.mmap`-backed ndarray.

It looks like scipy didn't hit this because they dropped this test (although not the surrounding text) in https://github.com/scipy/scipy/pull/14832/commits/6d40ad4adc883ec2474aea890e53aecaa34f021c as part of https://github.com/scipy/scipy/pull/14832.

Not quite sure where that leaves us. The easy thing is to follow Scipy's lead and drop the test, though I'd then go ahead and drop the text that indicates that `mmap` should appear. I don't know if the better solution would be to find an alternative test to ensure that the `mmap` functionality isn't damaged by future releases, and ensure it gets upstreamed into scipy.

**Closed** 2022-05-23 14:20 UTC
