### ISSUE TITLE
Flipping of qform x-orient

### ISSUE THREAD

**Issue by dpisner453** [nipy/nibabel#522] opened 2017-03-27 18:33 UTC
I am using nibabel to reslice my data from anistropic to isotropic voxels. The input image is of nifti compressed format. But I have experience flipping of the qform x-orient in the header upon writing the output. This does not appear to flip the actual image, just the header metadata. It could easily be resolved by setting the qform explicitly, but that would be a band-aid solution. Here is my code:

```Python
#!/bin/env python
import nibabel as nib
from dipy.align.reslice import reslice
from dipy.data import get_data
import os
import sys

fimg=sys.argv[1]
img=nib.load(fimg)
data=img.get_data()
data.shape
affine=img.get_affine()
zooms=img.get_header().get_zooms()[:3]
new_zooms=(2.,2.,2.)
data2, affine2 = reslice(data, affine, zooms, new_zooms)
img2 = nib.Nifti1Image(data2, affine2)
output = 'iso_' + str(fimg)
nib.save(img2, output)
```

**Comment by effigies** [comment] 2017-03-27 20:46
I can't reproduce this on an arbitrarily selected file. Can you make an anonymized file available that elicits this behavior?

Also, I wonder what happens if you use:

```Python
img2 = nib.Nifti1Image(data2, affine2, header=img.header)
```

In general, I would try not to throw away the header. I believe that a passed-in affine should override the header values, so that shouldn't be a danger.

NB: I modified your comment to get a monospace font and syntax highlighting.

**Comment by dpisner453** [comment] 2017-03-28 14:06
Adding the header option to nib.Nifti1Image does **not** fix this issue.  This only seems to happen when the qform_xorient in the header is the reverse of what is expected for standard LAS/RAS orientations. 

<img width="267" alt="screen shot 2017-03-28 at 8 58 00 am" src="https://cloud.githubusercontent.com/assets/16432683/24409065/c0ec6d04-1394-11e7-83a6-aa900eaabfcb.png">
<img width="264" alt="screen shot 2017-03-28 at 8 57 45 am" src="https://cloud.githubusercontent.com/assets/16432683/24409066/c0ed5552-1394-11e7-999f-ceaf2b963657.png">


See dropbox link to an example:
[`dwi image to be resliced`](https://www.dropbox.com/s/lkio684fmp25ll3/eddy_corrected_data.nii.gz?dl=0 )

**Comment by matthew-brett** [comment] 2017-03-28 14:10
When you create the new image, it has a different affine from the original header, so, when you create the new image, nibabel will set the qform and sform to match the affine.

If the qform does not in fact match the affine (and sform), that's definitely a bug.  Is that what you are seeing?

**Comment by dpisner453** [comment] 2017-03-28 14:41
I believe so, yes!

**Comment by matthew-brett** [comment] 2017-03-28 14:44
Could you post the output of:

```
print(img.get_qform())
print(img.get_sform())
```

from an offending image (one that you have written out, and believe to have an incorrect qform)?

**Comment by dpisner453** [comment] 2017-03-28 14:48
<img width="430" alt="screen shot 2017-03-28 at 9 46 27 am" src="https://cloud.githubusercontent.com/assets/16432683/24411437/8781d444-139b-11e7-8afc-8af7c9991972.png">
<img width="430" alt="screen shot 2017-03-28 at 9 47 07 am" src="https://cloud.githubusercontent.com/assets/16432683/24411444/8ab69d34-139b-11e7-8fb7-623a9e39495d.png">

...or in FSL lingo, this is what happens to the qform in the x dimension:

<img width="264" alt="screen shot 2017-03-28 at 9 47 51 am" src="https://cloud.githubusercontent.com/assets/16432683/24411500/af387e52-139b-11e7-9a78-efa9514c2106.png">

**Comment by matthew-brett** [comment] 2017-03-28 14:59
So the two printouts above are for before and after the conversion?

For both images the qform and sform match, so I think that is correct.  They both have right to left voxel orientation on disk, I guess, from the minus sign on the affine[0, 0] voxel value.

Are you saying that FSL `qform_orient` says 'Right to Left' before the conversion and 'Left to Right' after the conversion?  I'm afraid I don't know where FSL gets this information.  It's not a field I know of in the nifti1 header.

**Comment by effigies** [comment] 2017-03-28 15:08
I see LAS in both using `mri_info`.

```Shell
% mri_info *eddy*
Volume information for eddy_corrected_data.nii.gz
          type: nii
    dimensions: 256 x 256 x 37 x 55
   voxel sizes: 0.898400, 0.898400, 3.000002
          type: FLOAT (3)
           fov: 229.990
           dof: 0
        xstart: -115.0, xend: 115.0
        ystart: -115.0, yend: 115.0
        zstart: -55.5, zend: 55.5
            TR: 1000.00 msec, TE: 0.00 msec, TI: 0.00 msec, flip angle: 0.00 degrees
       nframes: 55
       PhEncDir: UNKNOWN
       FieldStrength: 0.000000
ras xform present
    xform info: x_r =  -1.0000, y_r =   0.0000, z_r =   0.0000, c_r =    -0.4442
              : x_a =   0.0000, y_a =   1.0000, z_a =   0.0000, c_a =    40.5392
              : x_s =   0.0000, y_s =   0.0000, z_s =   1.0000, c_s =    54.5399
Orientation   : LAS
Primary Slice Direction: axial

voxel to ras transform:
               -0.8984   0.0000   0.0000   114.5510
                0.0000   0.8984   0.0000   -74.4560
                0.0000   0.0000   3.0000    -0.9602
                0.0000   0.0000   0.0000     1.0000

voxel-to-ras determinant -2.42137

ras to voxel transform:
               -1.1131  -0.0000  -0.0000   127.5056
               -0.0000   1.1131  -0.0000    82.8762
               -0.0000  -0.0000   0.3333     0.3201
               -0.0000  -0.0000  -0.0000     1.0000


niiRead(): NIFTI_UNITS_UNKNOWN, assuming mm
WARNING: niiRead(): unknown time units 0 in iso_eddy_corrected_data.nii.gz
Volume information for iso_eddy_corrected_data.nii.gz
          type: nii
    dimensions: 115 x 115 x 56 x 55
   voxel sizes: 2.000000, 2.000000, 2.000000
          type: FLOAT (3)
           fov: 230.000
           dof: 0
        xstart: -115.0, xend: 115.0
        ystart: -115.0, yend: 115.0
        zstart: -56.0, zend: 56.0
            TR: 0.00 msec, TE: 0.00 msec, TI: 0.00 msec, flip angle: 0.00 degrees
       nframes: 55
       PhEncDir: UNKNOWN
       FieldStrength: 0.000000
ras xform present
    xform info: x_r =  -1.0000, y_r =   0.0000, z_r =   0.0000, c_r =    -0.4490
              : x_a =   0.0000, y_a =   1.0000, z_a =   0.0000, c_a =    40.5440
              : x_s =   0.0000, y_s =   0.0000, z_s =   1.0000, c_s =    55.0398
Orientation   : LAS
Primary Slice Direction: axial

voxel to ras transform:
               -2.0000   0.0000   0.0000   114.5510
                0.0000   2.0000   0.0000   -74.4560
                0.0000   0.0000   2.0000    -0.9602
                0.0000   0.0000   0.0000     1.0000

voxel-to-ras determinant -8

ras to voxel transform:
               -0.5000  -0.0000  -0.0000    57.2755
               -0.0000   0.5000  -0.0000    37.2280
               -0.0000  -0.0000   0.5000     0.4801
               -0.0000  -0.0000  -0.0000     1.0000
```

**Comment by dpisner453** [comment] 2017-03-28 15:12
The two printouts above are before and after the conversion, yes. It does indeed appear that within nibabel, the affines look to be correct. 

However, and as you noted, the qform_xorient flips from right-to-left to left-to-right after the conversion. My concern here is that if users are mixing nibabel functionality with FSL functionality (which I assumed is very common practice), that this could lead to some unforeseen issues downstream...

Chris-- good to know about the matching LAS-LAS orientaitons from mri_info. Thanks!

**Comment by matthew-brett** [comment] 2017-03-28 16:39
@dpisner453 - hum - I think I see the problem.  When the qform in the header has qform code 0 (unknown) then FSL does not see the X flip in the qform, for some reason.  By default, nibabel sets the qform code to 0, so when you save the image, and run `fslhd`, you get 'Left to Right' for the `qform_xorient`.

To avoid that, you could do this before saving the image:

```
img.header['qform_code'] = 2
```

**Comment by dpisner453** [comment] 2017-03-28 17:15
Brilliant. That works!

**Comment by effigies** [comment] 2017-03-29 00:46
Closing this. I think it'd probably good to ping FSL here, because it looks like a bug on their end, or at the very least an interpretation of the standard that doesn't match that of FreeSurfer or nibabel, and maybe they can clarify what they're doing. If people are depending on `fslhd` to make assertions about the orientation of their data, it should say what they intend, and what they intend should be absolutely clear.

**Closed by effigies** 2017-03-29 00:46 UTC

**Comment by matthew-brett** [comment] 2017-03-29 07:08
Hi,

I hope you're the right person to ask about this, but we just had a
discussion over at the nibabel issue tracker, about `qform_xorient`:

https://github.com/nipy/nibabel/issues/522

The upshot was that FSL appears to misread the x flip information when
the qform_code == 0 - we thought that was a bug.   Below there is
some Python code to show that a header with qform code == 0 appears to
be 'Left to Right', whereas the exact same header, with qform code ==
2, appears to be 'Right to Left'.    The affine indeed gives a Right
to Left orientation.

What do you think?

Cheers,

Matthew

In [1]: import numpy as np

In [2]: import nibabel as nib

In [3]: img = nib.Nifti1Image(np.zeros((2, 3, 4)), np.diag([-2, 3, 4, 1]))

In [4]: img.header['qform_code']
Out[4]: array(0, dtype=int16)

In [5]: nib.save(img, 'zero_qform.nii')

In [6]: !fslhd zero_qform.nii
filename       zero_qform.nii

sizeof_hdr     348
data_type      FLOAT64
dim0           3
dim1           2
dim2           3
dim3           4
dim4           1
dim5           1
dim6           1
dim7           1
vox_units      Unknown
time_units     Unknown
datatype       64
nbyper         8
bitpix         64
pixdim0        0.000000
pixdim1        2.000000
pixdim2        3.000000
pixdim3        4.000000
pixdim4        1.000000
pixdim5        1.000000
pixdim6        1.000000
pixdim7        1.000000
vox_offset     352
cal_max        0.0000
cal_min        0.0000
scl_slope      1.000000
scl_inter      0.000000
phase_dim      0
freq_dim       0
slice_dim      0
slice_name     Unknown
slice_code     0
slice_start    0
slice_end      0
slice_duration 0.000000
time_offset    0.000000
intent         Unknown
intent_code    0
intent_name
intent_p1      0.000000
intent_p2      0.000000
intent_p3      0.000000
qform_name     Unknown
qform_code     0
qto_xyz:1      2.000000  0.000000  0.000000  0.000000
qto_xyz:2      0.000000  3.000000  0.000000  0.000000
qto_xyz:3      0.000000  0.000000  4.000000  0.000000
qto_xyz:4      0.000000  0.000000  0.000000  1.000000
qform_xorient  Left-to-Right
qform_yorient  Posterior-to-Anterior
qform_zorient  Inferior-to-Superior
sform_name     Aligned Anat
sform_code     2
sto_xyz:1      -2.000000  0.000000  0.000000  0.000000
sto_xyz:2      0.000000  3.000000  0.000000  0.000000
sto_xyz:3      0.000000  0.000000  4.000000  0.000000
sto_xyz:4      0.000000  0.000000  0.000000  1.000000
sform_xorient  Right-to-Left
sform_yorient  Posterior-to-Anterior
sform_zorient  Inferior-to-Superior
file_type      NIFTI-1+
file_code      1
descrip
aux_file

In [7]: img.header['qform_code'] = 2

In [8]: nib.save(img, 'two_qform.nii')

In [10]: !fslhd two_qform.nii
filename       two_qform.nii

sizeof_hdr     348
data_type      FLOAT64
dim0           3
dim1           2
dim2           3
dim3           4
dim4           1
dim5           1
dim6           1
dim7           1
vox_units      Unknown
time_units     Unknown
datatype       64
nbyper         8
bitpix         64
pixdim0        0.000000
pixdim1        2.000000
pixdim2        3.000000
pixdim3        4.000000
pixdim4        1.000000
pixdim5        1.000000
pixdim6        1.000000
pixdim7        1.000000
vox_offset     352
cal_max        0.0000
cal_min        0.0000
scl_slope      1.000000
scl_inter      0.000000
phase_dim      0
freq_dim       0
slice_dim      0
slice_name     Unknown
slice_code     0
slice_start    0
slice_end      0
slice_duration 0.000000
time_offset    0.000000
intent         Unknown
intent_code    0
intent_name
intent_p1      0.000000
intent_p2      0.000000
intent_p3      0.000000
qform_name     Aligned Anat
qform_code     2
qto_xyz:1      -2.000000  0.000000  -0.000000  0.000000
qto_xyz:2      0.000000  3.000000  -0.000000  0.000000
qto_xyz:3      0.000000  0.000000  4.000000  0.000000
qto_xyz:4      0.000000  0.000000  0.000000  1.000000
qform_xorient  Right-to-Left
qform_yorient  Posterior-to-Anterior
qform_zorient  Inferior-to-Superior
sform_name     Aligned Anat
sform_code     2
sto_xyz:1      -2.000000  0.000000  0.000000  0.000000
sto_xyz:2      0.000000  3.000000  0.000000  0.000000
sto_xyz:3      0.000000  0.000000  4.000000  0.000000
sto_xyz:4      0.000000  0.000000  0.000000  1.000000
sform_xorient  Right-to-Left
sform_yorient  Posterior-to-Anterior
sform_zorient  Inferior-to-Superior
file_type      NIFTI-1+
file_code      1
descrip
aux_file

**Comment by matthew-brett** [comment] 2017-03-29 07:15
Hi Matthew,

If the qform_code is zero then the contents is not valid or usable so we revert to a default.
There really isn't any point interpreting anything in the qform fields if the qform_code is zero, so I would not call this a bug.  

In fact I would be more worried about software that trusts these fields when the qform_code is zero.  If that is the case it should use the sform instead.  If the sform_code is also zero then that image is without orientation information and really is borderline unusable.  We flag this case in our code and I'm tempted to make it so that FSL won't work with these images at all as they really are not properly formed nifti files at that point and there is a strong possibility of things going badly wrong in a pipeline if one such image was allowed to enter it.  Anyway, that's my view.

Cheers,
	MJ

**Comment by matthew-brett** [comment] 2017-03-29 07:21
Hi,

Thanks for the reply.

On Wed, Mar 29, 2017 at 8:14 AM, Mark Jenkinson
<mark.jenkinson@ndcn.ox.ac.uk> wrote:
> Hi Matthew,
>
> If the qform_code is zero then the contents is not valid or usable so we revert to a default.
> There really isn't any point interpreting anything in the qform fields if the qform_code is zero, so I would not call this a bug.

I guess the argument here would be FSL appears to interpret the qform
fields in `fslhd` - wrongly - even though the code is 0.  So, it would
make perfect sense of `qform_xorient` was something like 'unknown',
but it seems to me it is tempting fate to flip to a default 'Left to
Right' in that situation.

I have no idea whether anyone is using that information - I hope not -
but if they are, things could get ugly.

Cheers 2,

Matthew

**Comment by matthew-brett** [comment] 2017-03-29 07:29
Hi,

I kind of agree that unknown would be better and maybe we'll move to that in the future.

If anyone is using qform information (either directly from the header or via fslhd) without checking that the qform_code is non-zero, then they are not following the standard and will get into trouble either way, so we aren't really much different from just mining the header info directly.

I hope that no-one in nipy has been ignoring the qform codes!

Cheers,
	MJ

**Comment by matthew-brett** [comment] 2017-03-29 07:32
On Wed, Mar 29, 2017 at 8:29 AM, Mark Jenkinson
<mark.jenkinson@ndcn.ox.ac.uk> wrote:
> Hi,
>
> I kind of agree that unknown would be better and maybe we'll move to that in the future.
>
> If anyone is using qform information (either directly from the header or via fslhd) without checking that the qform_code is non-zero, then they are not following the standard and will get into trouble either way, so we aren't really much different from just mining the header info directly.
>
> I hope that no-one in nipy has been ignoring the qform codes!

Of course not!  All our users are impeccably trained!

:)

Matthew
