### ISSUE TITLE
gifti read fails

### ISSUE THREAD

**Issue by bpinsard** [nipy/nibabel#392] opened 2015-12-17 18:33 UTC
I do not know what has been changes in last commits but it seems that parser is added to GiftiImage class only if called using ```__init__```
if using nibabel.load of nibabel.gifti.read before ```GiftiImage.__init__``` has been called once, the following occurs

```
curv=nb.gifti.read('................/lh.white.32k.gii')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-d0fe17dcf62e> in <module>()
----> 1 curv=nb.gifti.read('............./lh.white.32k.gii')

/home/bpinsard/.virtualenvs/prod/lib/python2.7/site-packages/numpy/lib/utils.pyc in newfunc(*args, **kwds)
     98             """`arrayrange` is deprecated, use `arange` instead!"""
     99             warnings.warn(depdoc, DeprecationWarning)
--> 100             return func(*args, **kwds)
    101 
    102         newfunc = _set_function_name(newfunc, old_name)

/home/bpinsard/.virtualenvs/prod/lib/python2.7/site-packages/nibabel/gifti/giftiio.pyc in read(filename)
     29      """
     30     from ..loadsave import load
---> 31     return load(filename)
     32 
     33 

/home/bpinsard/.virtualenvs/prod/lib/python2.7/site-packages/nibabel/loadsave.pyc in load(filename, **kwargs)
     39         is_valid, sniff = image_klass.path_maybe_image(filename, sniff)
     40         if is_valid:
---> 41             return image_klass.from_filename(filename, **kwargs)
     42 
     43     raise ImageFileError('Cannot work out file type of "%s"' %

/home/bpinsard/.virtualenvs/prod/lib/python2.7/site-packages/nibabel/gifti/gifti.pyc in from_filename(klass, filename, buffer_size)
    603     def from_filename(klass, filename, buffer_size=35000000):
    604         file_map = klass.filespec_to_file_map(filename)
--> 605         img = klass.from_file_map(file_map, buffer_size=buffer_size)
    606         return img

/home/bpinsard/.virtualenvs/prod/lib/python2.7/site-packages/nibabel/gifti/gifti.pyc in from_file_map(klass, file_map, buffer_size)
    595             Returns a GiftiImage
    596          """
--> 597         parser = klass.parser(buffer_size=buffer_size)
    598         parser.parse(fptr=file_map['image'].get_prepare_fileobj('rb'))
    599         img = parser.img

AttributeError: type object 'GiftiImage' has no attribute 'parser'
```

**Comment by bcipolli** [comment] 2015-12-17 18:38
I can work at this tomorrow. This is a failure to deprecate an old codepath.

@bpinsard are you able to use `curv=nb.load('................/lh.white.32k.gii')`?

**Comment by bpinsard** [comment] 2015-12-17 18:45
@bcipolli nb.load is not working neither, if no GiftiImage has been instantiated before.

**Comment by bcipolli** [comment] 2015-12-17 18:47
ok, that's much worse; sorry to hear it. Important to fix, will work on it as soon as I can (tomorrow).

**Comment by effigies** [comment] 2015-12-17 19:04
@bpinsard Just to be sure, can you load your GiftiImages on the 2.0.2 release (8522d9d)?

**Comment by bpinsard** [comment] 2015-12-18 19:38
2.0.2 release doesn't have the bug.

**Comment by effigies** [comment] 2016-02-12 16:24
Had a peek. The problem is [here](https://github.com/nipy/nibabel/blob/master/nibabel/gifti/gifti.py#L427-L428):

```
class GiftiImage(xml.XmlSerializable, FileBasedImage):
    ...
    def __init__(...):
        ...
        from .parse_gifti_fast import GiftiImageParser
        GiftiImage.parser = GiftiImageParser
```

I believe this was done to avoid a circular dependency. @bpinsard could you see if 1fa44b74fc735bc3b9cc468e79219f628c5d07a0 fixes for you?

**Comment by bpinsard** [comment] 2016-02-12 16:41
no it doesn't fix because nibabel.gifti.parse_gifti_fast is not imported when I import nibabel.gifti then parser is not set.
I you want to test it yourself here you just have to do nibabel.gifti.read('path') with a freshly loaded nibabel.gifti module

**Comment by effigies** [comment] 2016-02-12 17:04
Yeah, probably should have looked to see there were gifti files to test on. Tested and pushed #405.

**Comment by bpinsard** [comment] 2016-02-12 19:43
great! that should do it.
thanks

**Comment by matthew-brett** [comment] 2016-08-07 01:11
@bpinsard - can we close this one?

**Comment by bpinsard** [comment] 2016-08-08 19:14
@matthew-brett  Yes! Thanks

**Closed** 2016-08-08 20:58 UTC
