### ISSUE TITLE
Test failure on Arm64

### ISSUE THREAD

**Issue by bcdarwin** [nipy/nibabel#861] opened 2020-01-11 02:50 UTC
Unfortunately I can't debug since I don't have such a machine set up; the tests were run by Hydra, the CI server for Nix/Nixpkgs for [this PR](https://github.com/NixOS/nixpkgs/pull/77472).

Release 3.0.0.

```
FAIL: nibabel.tests.test_volumeutils.test_a2f_nan2zero_range
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/iqysj9ccwz5xww339z07jyl6k5zc5074-python3.7-nose-1.3.7/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/nibabel-3.0.0/nibabel/tests/test_volumeutils.py", line 675, in test_a2f_nan2zero_range
    assert_array_equal([-128, -128, -128, nan_cast], back_arr)
  File "/nix/store/7k6dbm0p5imsnivp1xshbzkj30i28cjq-python3.7-numpy-1.18.0/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 936, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/nix/store/7k6dbm0p5imsnivp1xshbzkj30i28cjq-python3.7-numpy-1.18.0/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 846, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal
Mismatched elements: 1 / 4 (25%)
Max absolute difference: 1
Max relative difference: 1.0
 x: array([-128, -128, -128,    0])
 y: array([-128, -128, -128,   -1], dtype=int8)
----------------------------------------------------------------------
Ran 7671 tests in 227.364s
```

**Comment by effigies** [comment] 2020-01-11 03:42
This code is quite old and stable at this point, so my first inclination would be to look to see what's new in the environment.

Has Nix been packaging for Arm64 for a few versions, or is it just starting? It would be good to know if we're seeing this because now we're looking for it, or if something else has changed.

Assuming these tests aren't new, could we verify that this replicates with older versions of numpy?

**Comment by bcdarwin** [comment] 2020-01-11 04:12
I can look into this tomorrow, but my first suspicion is that it's somehow related to long floats just as #860 was.

**Comment by matthew-brett** [comment] 2020-01-11 10:33
It might well be something funny with long doubles.   Can you put a guard in to print out what `dt` is, when the test errors?

**Comment by bcdarwin** [comment] 2020-01-12 00:20
From examining [the Hydra builds](https://hydra.nixos.org/job/nixpkgs/trunk/python37Packages.nibabel.aarch64-linux/all), the Arm64 build has been broken since January 2019, when we were building 2.3.1.  It looks like this same test began failing with the upgrade to 2.3.3.

**Comment by bcdarwin** [comment] 2020-01-12 00:36
@matthew-brett -- unfortunately I think debugging packages in this way is out of the scope of the Nixpkgs CI.  If I have time I'll see about testing this on an Arm device.

**Comment by effigies** [comment] 2020-01-12 00:49
I think Travis now has ARM64 builds. We should see about enabling one.

**Comment by matthew-brett** [comment] 2020-01-12 00:54
An ARM64 build is an excellent idea.

**Comment by kaczmarj** [comment] 2020-04-15 23:25
This probably isn't a good solution here because nibabel already has infrastructure in place to build wheels, but I wanted to include this for future readers. Docker has the ability to build and run images for different platforms, including arm64 and ppc64le. See https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/.

**Comment by kaczmarj** [comment] 2020-04-16 14:48
I ran nibabel's tests on arm64, and only one failed.

```
FAILED tests/test_volumeutils.py::test_a2f_nan2zero_range - AssertionError: 
1 failed, 4784 passed, 111 skipped, 6 xfailed, 5662 warnings in 2153.20s (0:35:53)
```

To reproduce, run nibabel in an arm64 docker image:

```
# Register qemu interpreter things to be able to run arm64 etc on amd64
docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
docker run --rm -it -w /tmp/for-testing --platform linux/aarch64 kaczmarj/nibabel:latest
pytest --doctest-modules -v --pyargs nibabel
```

**Comment by bcdarwin** [comment] 2020-04-16 16:25
This is the same test failure as I got on Hydra (Nixpkgs CI), so nice work creating a reprex that runs on x64.

**Comment by effigies** [comment] 2020-05-15 13:37
Numpy got `aarch64` wheels up on https://anaconda.org/scipy-wheels-nightly/numpy/files, so we're able to replicate this bug on [Travis](https://travis-ci.com/github/nipy/nibabel/jobs/334565978#L6204-L6255), now. (See #862.)

I'm not likely to have much time to fiddle with this until June, so others should feel completely welcome to take a stab at it.

**Comment by effigies** [comment] 2020-05-16 00:44
Using @kaczmarj's image and running `pytest --pdb nibabel/tests/test_volumeutils.py`, I can at least narrow the case down to `float128` on ARM64. Didn't have time to whittle it down to a minimal reproduction.

**Comment by effigies** [comment] 2020-05-24 23:03
The issue turned out to be that `np.float64(np.nan).astype(np.int8)` is not the same as `np.float128(np.nan).astype(np.int8)` on Arm64.

The fix turns out to be quite simple: 5434b330a6c65ca122eb53f883b5c01bcf78395a

Would anybody care to review #862?

**Comment by effigies** [comment] 2020-05-27 16:37
This should be resolved in master and will be fixed in the next bug-fix release.

@bcdarwin That can come quickly, if this will be useful to Arch. If you already have a workaround, then we can wait and see if any more bugs come up before a new release. Just let me know.

**Closed by effigies** 2020-05-27 16:37 UTC

**Comment by bcdarwin** [comment] 2020-05-27 16:55
Great!  It's just a question of marking the Arm build unbroken in the Nixpkgs repo.  Since I doubt there are many Arm users yet we can probably wait until a new release.

**Comment by effigies** [comment] 2020-05-27 16:59
I might wait until late June (after the OHBM hackathon) then, to see if anything comes up. But bug fix releases are cheap, so if it becomes useful to have an official version number with ARM support, just shout.
